### PR TITLE
Make MineProcess respect exploreForBlocks

### LINKED ISSUE #766: exploreForBlocks does not apply with #mine
When I turn exploreForBlocks on, it works with #goto (block)
but it does not work with #mine (block)

### LINKED ISSUE #1017: Bot doesn't search for blocks when there are none in his view (with exploreForBlocks enabled on .b mine)
## Some information
Operating system: Windows 10 Version 1903
Java version: 1.8.0_191
Minecraft version: 1.12.2
Baritone version: 1.2.9
Forge mods (if used): None

## Exception, error or logs
https://imgur.com/ETcgmPk
[latest.log](https://github.com/cabaletta/baritone/files/3694813/latest.log)

## How to reproduce
It happens when there are no chests in the range of the bot with .b mine, it just stops searching even when exploreForBlocks is set to true.

## Final checklist
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

### LINKED ISSUE #1637: #ExploreForBlocks not properly working, especially in connection with #LegitMine
I am a duplicate of #1017, #766 and #1320 but I try to explain the problem more in detail and maybe someone can merge these issues into my one.

Setting #ExploreForBlocks is not working as expected, especially if setting #LegitMine is used as well. My testing was done using #reset all every time and I set values by hand:
| LegitMine | ExploreForBlocks |   | Behavior    | as expected? |
|-----------|------------------|---|-------------|:------------:|
| False     | True             |   | not explore |      No      |
| False     | False            |   | not explore |      Yes     |
| True      | True             |   | explores    |      Yes     |
| True      | False            |   | explores    |      No      |

#### Conclusion
As you see we have two setting-choices which do not work as expected.
If we disable #LegitMine and enable #ExploreForBlocks it will not start exploring.
If we enable #LegitMine and disable #ExploreForBlocks it will still start exploring.

I think this inconsistent behavior is a bug and could be fixed, but this report will also help people having problems with #ExploreForBlocks and give them a nice overview (see table).

## Some information
Operating system: W10 x64
Java version: 1.8.0_251
Minecraft version: 1.12.2
Baritone version: 1.2.14
Forge mods (if used): -

#### Should not explore but does:
```
[20:18:21] [Client thread/INFO]: [CHAT] [Baritone] > mine 1 diamond_ore
[20:18:21] [Client thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]
[20:18:21] [Client thread/INFO]: [baritone.ke:a:-1]: Currently have 0 valid items
[20:18:21] [Client thread/INFO]: [baritone.ke:a:-1]: Currently have 0 valid items
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hg:a:-1]: 1955712 movements considered
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hg:a:-1]: Open set size: 36582
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hg:a:-1]: PathNode map size: 125478
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hg:a:-1]: 177792 nodes per second
[20:18:21] [pool-5-thread-4/INFO]: [baritone.hh:a:-1]: Path goes for 105.68348972285122 blocks
```

#### Should explore but does not:
```
[20:19:37] [Client thread/INFO]: [CHAT] [Baritone] > mine 1 diamond_ore
[20:19:37] [Client thread/INFO]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]
[20:19:37] [Client thread/INFO]: [CHAT] [Baritone] No locations for BlockOptionalMetaLookup{[BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]} known, cancelling
```

#### Case 1 (exploring when it shouldn't):
- #reset all
- #LegitMine true
- #ExploreForBlocks false
- #mine 1 diamond_ore

#### Case 2 (not exploring when it should):
- #reset all
- #LegitMine false
- #ExploreForBlocks true
- #mine 1 diamond_ore

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have included the version of Minecraft I'm running, baritone's version and forge mods (if used).
- [x] I have included logs, exceptions and / or steps to reproduce the issue.
- [x] I have not used any OwO's or UwU's in this issue.

### LINKED ISSUE #2733: better mining options
## Describe your suggestion
i would suggest that there should be an option to let baritone wander through the world and whenever it detects the block youre looking for, it mines it and after that, it proceedes to wander through the world until it finds more of them.

## Settings
it should be the same as the ".mine" command, maybe the block type, and radius of detection or that kind of stuff.

## Context
It would be a lot easier to mine Blocks when your not at the PC because you dont have to walk to another location if it doesent find any, it would be more automatized and you could do more AFK-Mining for example.

## PS
sorry if i just dident realize by now that such a function is allready implemented.

## Final checklist
- [x] I know how to properly use check boxes 
- [x] I have not used any OwO's or UwU's in this issue.

### PR DESCRIPTION
**Pull request by ZacSharp**
Previously, `MineProcess` explored depending on `legitMine`

It currently uses `legitMineYLevel` like before for `legitMine`, but there is also `exploreMaintainY` (used by `ExploreProcess`) or nothing (`GetToBlockProcess`) and I wonder if I should change exploring for ores without legit mode to use one of the alternatives. 
closes #2733
fixes #1637
fixes  #1017
fixes #766

### CODE REVIEW

**Comment by leijurv** [comment]
Why? Those issues are just people not reading the documentation of what each setting means?

People are used to #legitmine, for example Impact has a toggle setting for legitmine if I remember correctly. 

A core part about legitmine is that it walks through caves until it finds ores. If you do it like this, the default behavior becomes that it instantly exits because it doesn't immediately see any ores.

**Comment by leijurv** [comment]
Yeah idk I'm not convinced. What is the use case for this new behavior? (when legitmine=true but exploreforblocks=false) It seems to me like a footgun, a behavior that you'd never truly want Baritone to do.

**Comment by ZacSharp** [comment]
I can just make `legitMine` override `exploreForBlocks` when it is enabled, just tell me what you want. 

The points for keeping it like this are:
* I think it is more consistent to toggle *any* exploring for blocks with a setting called `exploreForBlocks`.
* Of course the documentation can mention such things, but I don't think good documentation is an excuse for confusing design.

But usability is also a big one and it is definitely more usable when `legitMine` always explores, regardless of what you want for `#goto` `legitMine` (and I really don't expect people to want exploring for `#goto` but not for `legitMine`)

Compromise would be adding `legitMineAlwaysExplore` with `true` as default, but I don't like that either.

**Comment by leijurv** [comment]
Wait, if legitmine overrided exploreforblocks to true, then wouldn't that make this PR do nothing?

**Comment by ZacSharp** [comment]
No, it would make mining with `legitMine == false` respect `exploreForBlocks`.

**Comment by leijurv** [comment]
OHhhhhhhh...

So when there's no ores in render distance at all, with legitmine false, now it would explore?

**Comment by ZacSharp** [comment]
Exactly

**Comment by ZacSharp** [comment]
@leijurv what should be the behaviour with `legitMine` now?

File: src/main/java/baritone/process/MineProcess.java [hunk 1]
```diff
@@ -188,10 +188,10 @@ private PathingCommand updateGoal() {
             return new PathingCommand(goal, legit ? PathingCommandType.FORCE_REVALIDATE_GOAL_AND_PATH : PathingCommandType.REVALIDATE_GOAL_AND_PATH);
         }
         // we don't know any ore locations at the moment
-        if (!legit) {
+        if (!Baritone.settings().exploreForBlocks.value) {
```
Comment (leijurv) [inline src/main/java/baritone/process/MineProcess.java:191]: Perhaps this could be `if (!legit && !Baritone.settings().exploreForBlocks.value) {`

Would that still work for what you're trying to do with this PR?

Comment (ZacSharp) [reply src/main/java/baritone/process/MineProcess.java:191]: Yes, the only case I definitely want to change is `exploreForBlocks true` + `legitMine false`, which would still work.

Comment (leijurv) [reply src/main/java/baritone/process/MineProcess.java:191]: Okay let's do that then. I can see the benefit of that and that makes sense, and this way it won't have too bad of backwards incompatibility. 👍

**Comment by ItzAmirreza** [comment]
I think I need to reopen this issue since I'm facing a similar issue. Currently, if you try to mine with legitMine false and exploreForBlocks true, it does search and doesn't give up(which this pull requested fixed) until it finds an ore, then, when the first set of ores it found get mined, and there is none nearby anymore, it gives up again.
